// <auto-generated />
using System;
using CatFacts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatFacts.Migrations
{
    [DbContext(typeof(CatFactsDbContext))]
    partial class CatFactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatFacts.Models.CatFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CatFacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 7, 15, 50, 48, 0, DateTimeKind.Unspecified),
                            Fact = "A cat's nose is as unique as a human's fingerprint.",
                            Length = 51
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 7, 15, 50, 50, 0, DateTimeKind.Unspecified),
                            Fact = "A cat will tremble or shiver when it is in extreme pain.",
                            Length = 56
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 7, 15, 50, 51, 0, DateTimeKind.Unspecified),
                            Fact = "Cats have 3 eyelids.",
                            Length = 20
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 7, 15, 50, 52, 0, DateTimeKind.Unspecified),
                            Fact = "In 1987 cats overtook dogs as the number one pet in America.",
                            Length = 60
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 15, 50, 53, 0, DateTimeKind.Unspecified),
                            Fact = "The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for “cat.”",
                            Length = 132
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 7, 16, 38, 15, 0, DateTimeKind.Unspecified),
                            Fact = "In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.",
                            Length = 108
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 7, 16, 41, 31, 0, DateTimeKind.Unspecified),
                            Fact = "A cat's nose is as unique as a human's fingerprint.",
                            Length = 51
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 9, 7, 16, 42, 9, 0, DateTimeKind.Unspecified),
                            Fact = "A tomcat (male cat) can begin mating when he is between 7 and 10 months old.",
                            Length = 76
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 9, 7, 16, 50, 57, 0, DateTimeKind.Unspecified),
                            Fact = "The strongest climber among the big cats, a leopard can carry prey twice its weight up a tree.",
                            Length = 94
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 9, 7, 16, 58, 20, 0, DateTimeKind.Unspecified),
                            Fact = "Cats, especially older cats, do get cancer. Many times this disease can be treated successfully.",
                            Length = 96
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 11, 0, DateTimeKind.Unspecified),
                            Fact = "The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.",
                            Length = 192
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 12, 0, DateTimeKind.Unspecified),
                            Fact = "The Maine Coone is the only native American long haired breed.",
                            Length = 62
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 13, 0, DateTimeKind.Unspecified),
                            Fact = "Cats spend nearly 1/3 of their waking hours cleaning themselves.",
                            Length = 64
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 14, 0, DateTimeKind.Unspecified),
                            Fact = "It has been scientifically proven that owning cats is good for our health and can decrease the occurrence of high blood pressure and other illnesses.",
                            Length = 149
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 15, 0, DateTimeKind.Unspecified),
                            Fact = "Cats can judge within 3 inches the precise location of a sound being made 1 yard away.",
                            Length = 86
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 15, 0, DateTimeKind.Unspecified),
                            Fact = "A cat can spend five or more hours a day grooming himself.",
                            Length = 58
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 17, 0, DateTimeKind.Unspecified),
                            Fact = "When your cats rubs up against you, she is actually marking you as 'hers' with her scent. If your cat pushes his face against your head, it is a sign of acceptance and affection.",
                            Length = 137
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 18, 0, DateTimeKind.Unspecified),
                            Fact = "Ailurophile is the word cat lovers are officially called.",
                            Length = 57
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 19, 0, DateTimeKind.Unspecified),
                            Fact = "Cats have the largest eyes of any mammal.",
                            Length = 41
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 20, 0, DateTimeKind.Unspecified),
                            Fact = "Cats have the largest eyes of any mammal.",
                            Length = 41
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 21, 0, DateTimeKind.Unspecified),
                            Fact = "The heaviest cat on record is Himmy, a Tabby from Queensland, Australia. He weighed nearly 47 pounds (21 kg). He died at the age of 10.",
                            Length = 135
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 22, 0, DateTimeKind.Unspecified),
                            Fact = "In Ancient Egypt, when a person's house cat passed away, the owner would shave their eyebrows to reflect their grief.",
                            Length = 117
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 23, 0, DateTimeKind.Unspecified),
                            Fact = "Unlike humans, cats cannot detect sweetness which likely explains why they are not drawn to it at all.",
                            Length = 102
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 24, 0, DateTimeKind.Unspecified),
                            Fact = "Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.",
                            Length = 167
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 25, 0, DateTimeKind.Unspecified),
                            Fact = "A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.",
                            Length = 116
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 26, 0, DateTimeKind.Unspecified),
                            Fact = "A cat's nose is as unique as a human's fingerprint.",
                            Length = 51
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 27, 0, DateTimeKind.Unspecified),
                            Fact = "While many cats enjoy milk, it will give some cats diarrhea.",
                            Length = 60
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 27, 0, DateTimeKind.Unspecified),
                            Fact = "Statistics indicate that animal lovers in recent years have shown a preference for cats over dogs!",
                            Length = 98
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 28, 0, DateTimeKind.Unspecified),
                            Fact = "The strongest climber among the big cats, a leopard can carry prey twice its weight up a tree.",
                            Length = 94
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 9, 7, 17, 26, 30, 0, DateTimeKind.Unspecified),
                            Fact = "Cats are subject to gum disease and to dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.",
                            Length = 133
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
